name: "Checkout, Setup Node and install dependencies"
description: "Checkout, Setup Node and install dependencies"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 24.7.0
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
