services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zeity
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc
    restart: "no"
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 10 &&
        mc alias set local http://minio:9000 minio minio123 &&
        mc mb local/zeity || true
      "

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  zeity:
    build:
      context: .
      dockerfile: ./apps/zeity/Dockerfile
    depends_on:
      - postgres
      - maildev
      - minio
    ports:
      - 3000:3000
    environment:
      ZEITY_DATABASE_URL: postgresql://postgres:postgres@postgres/zeity
      ZEITY_MAILER_SMTP_HOST: maildev
      ZEITY_MAILER_SMTP_PORT: 1025
      ZEITY_S3_END_POINT: http://minio:9000
      ZEITY_S3_ACCESSKEY: minio
      ZEITY_S3_SECRETKEY: minio123
      ZEITY_S3_BUCKET: zeity
      ZEITY_SESSION_PASSWORD: abcdefghijklmnopqrstuvwxyz1234567890
      NODE_ENV: production

volumes:
  pg-data:
  minio-data:
